emprunter.c
void emprunterUnLivre(MYSQL *conn)
Referenced by instruction.
void deposer_livre(MYSQL *conn)
Referenced by instruction.
void liste_emprunt(MYSQL *conn)
Referenced by instruction.