menu.h
void menu()
Referenced by instruction.
void menu_admin()
Referenced by instruction.
void instruction()
Referenced by main.