.TH "Header/adherant.h" 3 "Mon Apr 26 2021" "Version v1.0.3" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Header/adherant.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBliste_Adeherant\fP (MYSQL *\fBconnexion\fP)"
.br
.ti -1c
.RI "void \fBajouter_adherant\fP (MYSQL *con)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void ajouter_adherant (MYSQL * con)"

.PP
Definition at line 28 of file adherant\&.c\&.
.SS "void liste_Adeherant (MYSQL * connexion)"

.PP
Definition at line 6 of file adherant\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
