.TH "Header/connexion.h" 3 "Mon Apr 26 2021" "Version v1.0.3" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Header/connexion.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBconnexion\fP (MYSQL *conn)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void connexion (MYSQL * conn)"

.PP
Definition at line 7 of file connexion\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
