.TH "Source/connexion.c" 3 "Mon Apr 26 2021" "Version v1.0.3" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/connexion.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <mysql/mysql\&.h>\fP
.br
\fC#include '\&.\&./Header/connexion\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBconnexion\fP (MYSQL *conn)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void connexion (MYSQL * conn)"

.PP
Definition at line 7 of file connexion\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
