.TH "Source/emprunter.c" 3 "Mon Apr 26 2021" "Version v1.0.3" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/emprunter.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <mysql/mysql\&.h>\fP
.br
\fC#include '\&.\&./Header/emprunter\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBemprunterUnLivre\fP (MYSQL *conn)"
.br
.ti -1c
.RI "void \fBdeposer_livre\fP (MYSQL *conn)"
.br
.ti -1c
.RI "void \fBliste_emprunt\fP (MYSQL *conn)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void deposer_livre (MYSQL * conn)"

.PP
Definition at line 57 of file emprunter\&.c\&.
.SS "void emprunterUnLivre (MYSQL * conn)"

.PP
Definition at line 6 of file emprunter\&.c\&.
.SS "void liste_emprunt (MYSQL * conn)"

.PP
Definition at line 92 of file emprunter\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
