.TH "Source/livre.c" 3 "Mon Apr 26 2021" "Version v1.0.3" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/livre.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <mysql/mysql\&.h>\fP
.br
\fC#include '\&.\&./Header/livre\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBListe_Livre\fP (MYSQL *\fBconnexion\fP)"
.br
.ti -1c
.RI "void \fBinsere_livre\fP (MYSQL *conn)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void insere_livre (MYSQL * conn)"

.PP
Definition at line 29 of file livre\&.c\&.
.SS "void Liste_Livre (MYSQL * connexion)"

.PP
Definition at line 6 of file livre\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
