.TH "Source/menu.c" 3 "Mon Apr 26 2021" "Version v1.0.3" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/menu.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <mysql/mysql\&.h>\fP
.br
\fC#include '\&.\&./Header/menu\&.h'\fP
.br
\fC#include '\&.\&./Header/livre\&.h'\fP
.br
\fC#include '\&.\&./Header/adherant\&.h'\fP
.br
\fC#include '\&.\&./Header/emprunter\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmenu\fP ()"
.br
.ti -1c
.RI "void \fBmenu_admin\fP ()"
.br
.ti -1c
.RI "void \fBinstruction\fP (MYSQL *con)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void instruction (MYSQL * con)"

.PP
Definition at line 33 of file menu\&.c\&.
.SS "void menu ()"

.PP
Definition at line 10 of file menu\&.c\&.
.SS "void menu_admin ()"

.PP
Definition at line 21 of file menu\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
