.TH "Header/menu.h" 3 "Mon Apr 26 2021" "Version v1.0.3" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Header/menu.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBmenu\fP ()"
.br
.ti -1c
.RI "void \fBmenu_admin\fP ()"
.br
.ti -1c
.RI "void \fBinstruction\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void instruction ()"

.SS "void menu ()"

.PP
Definition at line 10 of file menu\&.c\&.
.SS "void menu_admin ()"

.PP
Definition at line 21 of file menu\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
